# fly.toml app configuration file generated for n8n-on-render on 2025-06-04T05:17:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-on-render'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
