services:
  - type: web
    name: n8n
    env: docker
    plan: starter # Assurez-vous d'utiliser au moins le plan starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: monMotDePasse
      - key: N8N_PORT
        value: "10000"
      - key: PORT
        value: "10000"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: n8n-on-render-7wc9.onrender.com
      - key: N8N_WEBHOOK_URL
        value: https://n8n-on-render-7wc9.onrender.com
