services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: monMotDePasse
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_TUNNEL_URL
        fromService:
          type: web
          name: n8n
          property: url
      - key: N8N_EDITOR_BASE_URL
        fromService:
          type: web
          name: n8n
          property: url
